import { CalendarDays, Check, Download, Pencil, Plus, Search, Trash2, Users, X } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import toast from 'react-hot-toast';
import api from '../api.js';
import Modal from '../components/Modal.jsx';
import EmptyState from '../components/EmptyState.jsx';

const blank={name:'',description:'',date:'',status:'scheduled',users:[]};
const formatDate=d=>new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(d));
export default function Events(){
  const [events,setEvents]=useState([]),[allUsers,setAllUsers]=useState([]),[modal,setModal]=useState(false),[editing,setEditing]=useState(null),[form,setForm]=useState(blank),[query,setQuery]=useState(''),[saving,setSaving]=useState(false),[loading,setLoading]=useState(true);
  const load=async()=>{setLoading(true);try{const [e,u]=await Promise.all([api.get('/events'),api.get('/users',{params:{limit:5000}})]);setEvents(e.data.events);setAllUsers(u.data.users);}finally{setLoading(false)}};useEffect(()=>{load()},[]);
  const filtered=useMemo(()=>allUsers.filter(u=>`${u.name} ${u.uniqueId} ${u.email}`.toLowerCase().includes(query.toLowerCase())),[allUsers,query]);
  const openAdd=()=>{setEditing(null);setForm(blank);setQuery('');setModal(true)};const openEdit=e=>{setEditing(e);setForm({name:e.name,description:e.description||'',date:e.date.slice(0,10),status:e.status,users:e.users.map(u=>u._id)});setModal(true)};
  const toggle=id=>setForm({...form,users:form.users.includes(id)?form.users.filter(x=>x!==id):[...form.users,id]});
  const save=async(e)=>{e.preventDefault();setSaving(true);try{editing?await api.put(`/events/${editing._id}`,form):await api.post('/events',form);toast.success(editing?'Event updated':'Event created');setModal(false);load()}catch(e){toast.error(e.response?.data?.message||'Could not save event.')}finally{setSaving(false)}};
  const remove=async(e)=>{if(!window.confirm(`Delete “${e.name}”?`))return;try{await api.delete(`/events/${e._id}`);toast.success('Event deleted');load()}catch(err){toast.error(err.response?.data?.message||'Could not delete event.')}};
  const download=async(e)=>{try{const r=await api.get(`/events/${e._id}/export`,{responseType:'blob'});const a=document.createElement('a');a.href=URL.createObjectURL(r.data);a.download=`${e.name.replace(/[^a-z0-9]/gi,'-').toLowerCase()}-participants.xlsx`;a.click();URL.revokeObjectURL(a.href);toast.success('Excel file downloaded')}catch{toast.error('Could not download the event.')}};
  return <div className="page-content">
    <div className="action-bar"><div className="section-intro"><strong>Event collections</strong><span>Each event keeps a reusable snapshot of selected users.</span></div><button className="primary-btn" onClick={openAdd}><Plus size={17}/> Create event</button></div>
    <section className="event-grid">{events.map(e=><article className="event-card" key={e._id}><div className="event-card-top"><div className="event-icon"><CalendarDays size={21}/></div><span className={`status ${e.status}`}>{e.status}</span></div><h2>{e.name}</h2><p>{e.description||'No description added.'}</p><div className="event-meta"><span><CalendarDays size={16}/>{formatDate(e.date)}</span><span><Users size={16}/>{e.users.length} participant{e.users.length!==1?'s':''}</span></div><div className="avatar-stack">{e.users.slice(0,5).map(u=><i key={u._id}>{u.name[0]}</i>)}{e.users.length>5&&<i>+{e.users.length-5}</i>}</div><div className="event-card-actions"><button className="download-btn" onClick={()=>download(e)} disabled={!e.users.length}><Download size={17}/> Download Excel</button><button className="icon-btn" onClick={()=>openEdit(e)}><Pencil size={16}/></button><button className="icon-btn danger" onClick={()=>remove(e)}><Trash2 size={16}/></button></div></article>)}</section>
    {!loading&&!events.length&&<section className="panel"><EmptyState icon={CalendarDays} title="No events yet" text="Create an event, select users, and export their details whenever you need them." action={<button className="primary-btn" onClick={openAdd}><Plus size={17}/> Create first event</button>}/></section>}{loading&&<div className="loading-state">Loading events…</div>}
    <Modal open={modal} onClose={()=>setModal(false)} title={editing?'Edit event':'Create an event'} subtitle="Add event details and choose participants." wide><form onSubmit={save} className="event-form"><div className="event-fields"><label>Event name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="e.g. September vendor payout" required/></label><div className="two-fields"><label>Event date<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})} required/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="draft">Draft</option><option value="scheduled">Scheduled</option><option value="completed">Completed</option></select></label></div><label>Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Optional notes about this event" rows="4"/></label><div className="selection-summary"><Users size={20}/><div><strong>{form.users.length} selected</strong><span>Participant records will be included in the Excel export.</span></div></div></div><div className="user-picker"><div className="picker-head"><div><strong>Select users</strong><span>{allUsers.length} available</span></div>{form.users.length>0&&<button type="button" className="text-btn" onClick={()=>setForm({...form,users:[]})}>Clear all</button>}</div><div className="table-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search users…"/></div><div className="picker-list">{filtered.map(u=><button type="button" className={`picker-user ${form.users.includes(u._id)?'selected':''}`} onClick={()=>toggle(u._id)} key={u._id}><span className="picker-check">{form.users.includes(u._id)&&<Check size={14}/>}</span><span className="mini-avatar">{u.name[0]}</span><span><strong>{u.name}</strong><small>{u.uniqueId} · {u.bankName}</small></span></button>)}{!filtered.length&&<div className="inline-empty">No matching users.</div>}</div></div><div className="modal-actions event-submit"><button type="button" className="secondary-btn" onClick={()=>setModal(false)}>Cancel</button><button className="primary-btn" disabled={saving}>{saving?'Saving…':editing?'Save changes':'Create event'}</button></div></form></Modal>
  </div>;
}
